### ISSUE TITLE
After the latest update, action use reports "MATTERMOST_WEBHOOK_URL" not set

### ISSUE THREAD

**Issue by jwoytek** [mattermost/action-mattermost-notify#14]
Starting this morning, I'm getting a message when trying to use this action that "MATTERMOST_WEBHOOK_URL" is not set, but it is set in the environment where the action is called. This was previously working as of Friday last week. 

```
Run mattermost/action-mattermost-notify@master
  with:
    PAYLOAD_FILENAME: mattermost.json
  env:
    MATTERMOST_WEBHOOK_URL: [redacted]
    MATTERMOST_CHANNEL: devops
    MATTERMOST_USERNAME: github
Error: Input required and not supplied: MATTERMOST_WEBHOOK_URL
```

**Comment by AJPcodes** [comment]
Seconding this same issue.

**Comment by toninis** [comment]
Hello . 

We recently changed the way this action work . Check https://github.com/mattermost/action-mattermost-notify/pull/13 . 
We migrated this action for significant performance boost . You can check documentation [here](https://github.com/mattermost/action-mattermost-notify?tab=readme-ov-file#usage) in order to migrate . 

If you do not want to migrate to the new way you can still pin your action to the previous tag https://github.com/mattermost/action-mattermost-notify/releases/tag/1.1.0 

```yaml
mattermost/action-mattermost-notify@1.1.0
```

**Comment by jwoytek** [comment]
> Hello .
> 
> We recently changed the way this action work . Check #13 . We migrated this action for significant performance boost . You can check documentation [here](https://github.com/mattermost/action-mattermost-notify?tab=readme-ov-file#usage) in order to migrate .

Thank you for updating the documentation to reflect the new reality. It was rather unfortunate that Monday morning involved a bit of panicked debugging of why all of our pipeline jobs suddenly started to fail.
